name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ballerina
      uses: ballerina-platform/setup-ballerina@v1.1.3
      with:
        version: 2201.12.10

    - name: Cache Ballerina dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.ballerina
          target
        key: ${{ runner.os }}-ballerina-${{ hashFiles('Dependencies.toml') }}
        restore-keys: |
          ${{ runner.os }}-ballerina-

    - name: Check code formatting
      run: |
        bal format
        if [ -n "$(git status --porcelain)" ]; then
          echo "Code is not formatted. Please run 'bal format' locally."
          git diff
          exit 1
        fi

    - name: Build project
      run: bal build

    - name: Run tests
      run: bal test

    - name: Run OSV Scanner for dependency vulnerabilities
      uses: google/osv-scanner/actions/scanner@v1.9.0
      continue-on-error: true
      with:
        scan-args: |
          --lockfile=Dependencies.toml
